@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber
actor "Client" as User

    participant "Browser" as FE
    participant "API" as API


User -> FE : I want to have today’s sunrise and sunset hours on the front/main page
activate FE

FE -> API : GET/https://api.sunrise-sunset.org/json
activate API

API --> FE : Json, status ok
deactivate API

FE --> User : show sunrise and sunset hours
deactivate FE



@enduml